name: Testing taskiq-aio-pika

on: [push, pull_request]

jobs:
  lint:
    strategy:
      matrix:
        cmd:
          - black
          - flake8
          - isort
          - mypy
          - autoflake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "poetry"
      - name: Install deps
        run: poetry install
      - name: Run lint check
        run: poetry run pre-commit run -a ${{ matrix.cmd }}
  pytest:
    services:
      rabbit:
        image: heidiks/rabbitmq-delayed-message-exchange:latest
        env:
          RABBITMQ_DEFAULT_USER: "guest"
          RABBITMQ_DEFAULT_PASS: "guest"
          RABBITMQ_DEFAULT_VHOST: "/"
        options: >-
          --health-cmd="rabbitmq-diagnostics check_running -q"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=8
        ports:
          - 5672:5672
    strategy:
      matrix:
        py_version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.py_version }}"
          cache: "poetry"
      - name: Install deps
        run: poetry install
      - name: Run pytest check
        run: poetry run pytest -vv -n auto --cov="taskiq_aio_pika" .
